id: I74634A41
legacy_id: P008249
ocr_import_info:
  bdrc_scan_id: W1KG13823
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T05:33:51'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T06:47:07.828681+00:00'
last_modified: 2022-08-31 14:47:18.455582
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG13823
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG13823
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྫོགས་ཆེན་དགོན་གྱི་ལོ་རྒྱུས།
  author: མི་ཉག་པ་རྒྱལ་དབང་ཆོས་ཀྱི་ཉི་མ།
statistics:
  ocr_word_mean_confidence_index: 0.795719162305069
  ocr_word_median_confidence_index: 0.8999999761581421
quality: null
bases:
  I1KG16108:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG16108
      total_pages: 192
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG16108.txt
    statistics:
      ocr_word_median_confidence_index: 0.8999999761581421
      ocr_word_mean_confidence_index: 0.795719162305069
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
