id: P008249
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 13:10:41.431209
source_metadata:
  id: bdr:W1KG13823
  title: རྫོགས་ཆེན་དགོན་གྱི་ལོ་རྒྱུས།
  author: ''
  volumes:
    e76053aa3c124eefa7f36a42030b29ec:
      image_group_id: I1KG16108
      title: ''
      volume_number: 1
      total_pages: 192
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
